name: Node.js CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [14.x]  # Перелік версій Node.js для тестування

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Env Capture
        run: cp /home/david/secret/.env /home/david/backend/_work/dashboard-backend/dashboard-backend/

      - name: Install dependendencies.
        run: 
          npm install
 
      - name: pm2 stop 0
        run: pm2 stop 0
 
      - name: pm2 start 0
        run: pm2 start 0
 
      - name: pm2 save
        run: pm2 save